---
- name: Playbook to add hosts to host collection
  hosts: sat6.shadowman.dev
  gather_facts: no

  vars:
    coll_name: "{{ survey_coll_name }}"
    org_name: "Shadow Man"

  tasks:
#  - name: Check if host exists in Satellite
#    ansible.builtin.shell:
#      cmd: hammer --no-headers host list --organization "{{ org_name }}" --fields name --search "{{ item | replace(' ','') }}"

#  - name: Check if host is already in host collection
#    ansible.builtin.shell:
#      cmd:  hammer --no-headers host-collection host --name "{{ coll_name }}" --organization "{{ org_name }}" --fields name | grep "{{ item | replace(' ','') }}"

  - name: Add hosts to hosts collections
    ansible.builtin.shell:
      cmd: hammer --no-headers host-collection add-host --hosts "{{ item | replace(' ','') }}" --name "{{ coll_name }}" --organization "{{ org_name }}"