---
- name: Playbook to create host collection in Satellite from survey text
  hosts: sat.ofam.dev
  gather_facts: no

  tasks:
  - name: Create host collection "{{ coll_name }}" in Satellite
    ansible.builtin.shell:
      cmd: hammer --no-headers host-collection create --name "{{ coll_name }}" --organization "{{ org_name }}"
    tags:
      - addcolltag
  
  - name: Call TASK to add hosts to collection
    ansible.builtin.include_tasks: addhostcoll_task.yml
    loop: "{{ survey_add_hosts | split ('\n') }}"
    tags:
      - addhoststag

- name: Sync Inventory
  hosts: localhost
  connection: local
  gather_facts: no

  tasks: 
  - name: Sync AAP Satellite inventory source
    ansible.controller.inventory_source_update:
      inventory_source: "{{ inventory_source_name }}"
      inventory: "{{ inventory_name }}"
      wait: true