---
- name: Delete a host collection in Satellite
  hosts: sat6.shadowman.dev
  gather_facts: no

  vars:
    coll_name: "{{ survey_coll_name }}"
    org_name: "Shadow Man"

  tasks:
  - name: Delete host collection "{{ coll_name }}" in Satellite
    ansible.builtin.shell:
      cmd: hammer --no-headers host-collection delete --name "{{ coll_name }}" --organization "{{ org_name }}"
    tags:
      - delcoltag

- name: Sync Inventory
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    inventory_source_name: "Satellite Inventory"
    inventory_name: Sat6

  tasks: 
  - name: Update a single inventory source
    ansible.controller.inventory_source_update:
      inventory_source: "{{ inventory_source_name }}"
      inventory: "{{ inventory_name }}"
      wait: true