---
- name: Delete a host collection in Satellite
  hosts: sat6.shadowman.dev
  gather_facts: no

  vars:
    coll_name: "{{ survey_coll_name }}"

  tasks:
  - name: Delete host collection "{{ coll_name }}" in Satellite
    ansible.builtin.shell:
      cmd: hammer --no-headers host-collection delete --name "{{ coll_name }}" --organization "{{ org_name }}"
    tags:
      - delcoltag