---
- name: Project sat-coll
  hosts: localhost
  gather_facts: no

  vars:
    sat_user: "{{ username }}"
    sat_pw: "{{ password }}"
    sat_url: "{{ server_url }}"

  tasks:
  - name: "Create Foo host collection"
    redhat.satellite.host_collection:
      username: "{{ sat_user }}"
      password: "{{ sat_pw }}"
      server_url: "{{ sat_url }}"
      name: "NORMFoo"
      description: "Foo host collection for Foo servers"
      organization: "Shadow Man"
      state: present 
  
  - name: "Display hosts to be added"
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ survey_add_hosts | split ('\n')}}"

# create separate role or task??
#  - name: "get rest api info from Satellite"
#    ansible.builtin.uri:
#      url: "{{ sat_url }}/api/v2/hosts/{{ items }}"
#      method: GET
#      user: "{{ sat_user }}"
#      password: "{{ sat_pw }}"
#      force_basic_auth: true
#      validate_certs: false
#    register: restdata
#  - name: "get rest data"
#    ansible.builtin.debug:
#      msg: "{{ restdata }}"