---
- name: Project sat-coll
  hosts: sat6.shadowman.dev 
  gather_facts: no

  vars:
    sat_user: '{{ username }}'
    sat_pw: '{{ password }}'
    sat_url: '{{ server_url }}'

  tasks:

  - name: Create host collection
    theforeman.foreman.host_collection:
      username: '{{ sat_user }}'
      password: '{{ sat_pw }}'
      server_url: '{{ sat_url }}'
      name: "NORMFoo"
      description: "Foo host collection for Foo servers"
      organization: "Shadow Man"
      state: present
      tags:
        - makehostcoll 