---
- name: Project sat-coll
  hosts: localhost
  gather_facts: no

  vars:
    sat_user: "{{ username }}"
    sat_pw: "{{ password }}"
    sat_url: "{{ server_url }}"

  tasks:
  - name: "Create Foo host collection"
    redhat.satellite.host_collection:
      username: "{{ sat_user }}"
      password: "{{ sat_pw }}"
      server_url: "{{ sat_url }}"
      name: "NORMFoo"
      description: "Foo host collection for Foo servers"
      organization: "Shadow Man"
      state: present 
  
  - name: "Display hosts to be added"
    ansible.builtin.debug:
      msg: "{{ survey_add_hosts }}"
#      msg: "{{ item }}"
#    loop: "{{ survey_add_hosts | split ('\n')}}"