---
- name: Playbook to create host collection in Satellite from survey text
  hosts: sat6.shadowman.dev
  gather_facts: no

  vars:
#    sat_user: "{{ username }}"
#    sat_pw: "{{ password }}"
#    sat_url: "{{ server_url }}"
    coll_name: "{{ survey_coll_name }}"
    org_name: "Shadow Man"

  tasks:
#  - name: "Create Foo host collection"
#    redhat.satellite.host_collection:
#      username: "{{ sat_user }}"
#      password: "{{ sat_pw }}"
#      server_url: "{{ sat_url }}"
#      name: "NORMFoo"
#      description: "Foo host collection for Foo servers"
#      organization: "Shadow Man"
#      state: present 

  - name: Create host collection in Satellite using command-line 
    ansible.builtin.shell:
      cmd: hammer --no-headers host-collection create --name "{{ coll_name }}" --organization "{{ org_name }}"
      
  - name: "Display hosts to be added"
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ survey_add_hosts | split ('\n') }}"