---
- name: Test workflow 
  hosts: "foreman_hostcollection_{{ survey_coll_name | lower }}"
  gather_facts: no

  tasks:
  - name: ping the hosts passed in workflow from addhostcoll.yml
    ansible.builtin.ping:
